import "bootstrap/dist/css/bootstrap.min.css"
import AddBootstrap from "./AddBootstrap";
import Link from "next/link";
import type { Metadata } from "next";
import Nav from "./components/navbar";


export const metadata: Metadata = {
    title: "Next App - D1 + R2",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {



    return (
        <html lang="en">
            <body>
                <AddBootstrap />
                <Nav />
                <div className="container mt-5 mr-auto ml-auto mx-auto">
                    {children}
                </div>

            </body>
        </html>
    );
}
